# Generated by Django 5.2.10 on 2026-02-04 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('cis', '0040_add_highschool_geocoding'),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', models.JSONField(default=dict)),
                ('started_on', models.DateField(auto_now=True)),
                ('last_viewed_on', models.DateField(auto_now_add=True)),
                ('submitted_on', models.DateField(blank=True, null=True)),
                ('section_info', models.JSONField(default=dict)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fs_futurecourse_set', to='cis.academicyear')),
                ('teacher_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_futurecourse_set', to='cis.teachercoursecertificate')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fs_futurecourse_set', to='cis.term')),
            ],
            options={
                'unique_together': {('teacher_course', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='FutureSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_info', models.JSONField(blank=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('future_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='future_sections.futurecourse')),
            ],
        ),
        migrations.CreateModel(
            name='FutureProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', models.JSONField(default=dict)),
                ('started_on', models.DateField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fs_futureprojection_set', to='cis.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fs_futureprojection_set', to=settings.AUTH_USER_MODEL)),
                ('highschool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fs_futureprojection_set', to='cis.highschool')),
            ],
            options={
                'unique_together': {('academic_year', 'highschool')},
            },
        ),
    ]
