# Generated by Django 5.2.10 on 2026-02-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurecourse',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='submitted', max_length=20),
        ),
    ]
