# Generated by Django 5.2.17 on 2026-09-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_sections', '0003_futurecourse_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurecourse',
            name='review_round',
            field=models.PositiveIntegerField(default=0, help_text='The live review round. Incremented each time CE marks the request pending review; SectionRequestReview rows carrying an earlier round are finished rounds kept as history.'),
        ),
        migrations.AlterField(
            model_name='futurecourse',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending_review', 'Pending Review'), ('reviewed', 'Reviewed')], default='submitted', max_length=20),
        ),
    ]
