# Generated by Django 5.2.17 on 2026-09-03 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '__first__'),
        ('future_sections', '0004_futurecourse_review_round_alter_futurecourse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionRequestReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=50)),
                ('decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('not_approved', 'Not approved')], default='', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('future_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='future_sections.futurecourse')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_for_section_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_request_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['round', 'created_on'],
                'unique_together': {('future_course', 'reviewer', 'round')},
            },
        ),
    ]
