# Generated by Django 5.2.17 on 2026-09-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_sections', '0006_migrate_legacy_faculty_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionrequestreview',
            options={'ordering': ['round', 'weight', 'created_on']},
        ),
        migrations.AddField(
            model_name='futurecourse',
            name='review_paused_on',
            field=models.DateTimeField(blank=True, help_text='Set when a reviewer does not approve the request. While set, no reviewer is notified automatically: staff drive it by hand (Notify next stage, or reset to submitted). Not a status, so the lock, badges, filters and export are unaffected.', null=True),
        ),
        migrations.AddField(
            model_name='sectionrequestreview',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
