# Generated by Django 5.2.17 on 2026-09-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_sections', '0007_sequential_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionrequestreview',
            name='skipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skipped_section_request_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sectionrequestreview',
            name='decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('not_approved', 'Not approved'), ('skipped', 'Skipped')], default='', max_length=20),
        ),
    ]
